### ISSUE TITLE
SD Card Support

### ISSUE THREAD

**Issue by stoponerr** [flackbash/AudioAnchor#169] opened 2022-05-21 13:34 UTC
Device: crownlte - LineageOS 18.1

I use an external SD card for most of my media to save space for apps and files on the device memory and it would be nice if I could continue to leave my audio books on there and use your app.

**Comment by flackbash** [comment] 2022-05-22 10:07
LineageOS 18.1 is based on Android 11, so this is a duplicate of #111.
I have it on my agenda, but unfortunately it's a bigger issue with most likely a lot of changes involved.

**Closed by flackbash** 2022-05-22 10:07 UTC
