### ISSUE TITLE
Playing m4a files causes strange app behavior

### ISSUE THREAD

**Issue by peg5** [flackbash/AudioAnchor#64] opened 2020-07-16 17:24 UTC
I have three albums, in separate directories, whose songs are all in m4a format. When I try to play one, starting with the first track, the app seems to zoom through all the tracks without playing them. Once it gets to the last track, the app freezes, not responding to any input. I can't even hit Back to close the app.

I get the same experience for any one of these albums.

According to this github site, the app supports the m4a filetype.

VLC Media Player plays these files without error.

I am using a Motoral Moto E4, running Android 7.1.1. The problematic albums are saved to the SD card, not the internal storage.

**Comment by flackbash** [comment] 2020-07-29 18:46
That's strange. Do you have a link to these files / one file that is not working? That would help with debugging.

**Comment by flackbash** [comment] 2021-04-07 09:41
Closing this because issue is not currently reproducible.

**Closed by flackbash** 2021-04-07 09:41 UTC
Labels: bug, irreproducible
