### ISSUE TITLE
App cannot go landscape mode

### ISSUE THREAD

**Issue by suhridkhan** [flackbash/AudioAnchor#170] opened 2022-05-23 20:52 UTC
The app appears to be locked in vertical screen orientation, cannot go to landscape.
I intend to use the app in an Android head unit in the car, which is fixed in landscape. Please enable that this app can work in landscape. Otherwise, it's a great app.

**Comment by flackbash** [comment] 2022-06-06 10:16
Duplicate of #45. But the use case you describe is indeed a good motivation to implement this.

**Closed by flackbash** 2022-06-06 10:16 UTC
